version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./linuxBench:/var/www/html
  db:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: benchmark_ffmpeg
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql