global:
  scrape_interval: 5s #Scrape interval to every 15 seconds.
  evaluation_interval: 5s #Evaluate rules every 15 seconds.

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets:
        - 172.31.0.1:8080
  - job_name: "node"
    static_configs:
      - targets:
        - 172.31.0.1:9100
