version: '3.8'

services:
  # Angular Frontend Services
  angular-app:
    build:
      context: ./frontend/
      dockerfile: linuxBench/Dockerfile
    deploy:
      replicas: 5
    networks:
      - frontend

  # Nginx Load Balancer for Angular
  angular-lb:
    image: nginx:latest
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:4200"
    depends_on:
      - angular-app
    networks:
      - frontend

  # PHP Backend Services
  php-api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - PORT=80
    deploy:
      replicas: 5
    networks:
      - backend

  # Nginx Load Balancer for PHP
  php-api-lb:
    image: nginx:latest
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - php-api
    networks:
      - backend

  # MySQL Database Services
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: results
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend

  # cAdvisor for Monitoring
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
    networks:
      - monitoring

  # Prometheus for Data Collection
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  # Grafana for Data Visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  frontend:
  backend:
  monitoring:

volumes:
  mysql-data:
  grafana-data:
